### ISSUE TITLE
Do you know this project?

### ISSUE THREAD

**Issue by ruifortes** [anmonteiro/bucklescript#53]
https://grain-lang.org/

**Comment by anmonteiro** [comment]
I've heard about it, and know @phated is involved. I'm sure he'll be happy to answer any questions.

**Comment by ruifortes** [comment]
No questions, just to ensure you were aware.
Sujestion: a "Thanks anyway" doesn't sound as possive agressive

**Comment by anmonteiro** [comment]
It's hard to convey meaning in GitHub comments. I wasn't trying to be passive aggressive, and I appreciate you putting it on my radar.

**Comment by ruifortes** [comment]
Sure, I know cause I tend to sound agressive. :-)
