### ISSUE TITLE
Warning 29 is part of compilation flags

### ISSUE THREAD

**Issue by jchavarri** [anmonteiro/bucklescript#63]
In multiline strings without `\` at the end of the line, upstream bsb does not show warning 29 (either as error or warning) while with the fork it errors as:

```
Error (warning 29 [eol-in-string]): unescaped end-of-line in a string constant (non-portable code)
```

Example below has `bsconfig.json` like:

```
    "warnings": {
      "error": "+A-d"
    },
```

but a similar problem is visible without adding `warnings` property (warnings are shown in fork, while upstream does not show them).

[error_endline.zip](https://github.com/anmonteiro/bucklescript/files/6203097/error_endline.zip)

**Comment by jchavarri** [comment]
fwiw these are other warnings that are failing in this fork with `+A-d` but don't seem to appear in upstream compiler: 16, 44, 66.

**Comment by anmonteiro** [comment]
I think this is due to recent versions of OCaml expanding the cases where warnings are issued. I'd recommend disabling them as needed, and now I'm not sure we should merge #65

**Comment by jchavarri** [comment]
Agree :)

**Comment by anmonteiro** [comment]
ok great. closing this as "wontfix" then.
